[tool.pylint.message_control]

disable = [
    "invalid-name",
    "missing-function-docstring",
    "missing-module-docstring",
    "logging-fstring-interpolation",
]

[tool.black]
line-length = 90
skip-string-normalization = true
target-version = ['py311']

[tool.isort]
multi_line_output = 3
length_sort = true
include_trailing_comma = true  # Match black's style

# .isort.cfg
[settings]
line_length = 90  # Match black
