{
 "title": "Evidently Dashboard",
 "description": "Dashboard for monitoring evidently metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", temperature_drift FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidty Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", humidity_drift FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "ECO2 Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT eco2_drift, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}