name: Integration Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: main
      - name: install pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          exec "$SHELL"
      - name: setup environment
        run: |
          pip install pipenv
          pipenv lock
      - name: running integration tests
        run: |
          sudo chmod 777 ./integration-tests/run.sh
          make integration-test
