name: Unit tests

on:
  push:
    branches:
      - main
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: main
      
      - name: running unit tests
        run: |
          make test
