name: Unit tests

on:
  push:
    branches:
      - main
    

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: main
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: setup environment
        run: make install
      - name: running unit tests
        run: |
          make test
